os: linux
sudo: required
language: generic

install:
  - sudo apt-get update -qq
# - sudo apt-get install -y gcc-avr binutils-avr avr-libc
  - bash ./.build-avr-gcc.sh
  - avr-gcc --version

before_script:
  - wget https://github.com/stateos/IntrOS/archive/master.zip
  - unzip -q master.zip
  - mv IntrOS-master/IntrOS/* IntrOS/
  - rm -r IntrOS-master

script: make all GNUCC=avr-
